from Constants.path_track import (
    connect_pathes,
    RUN_ASSETS_FOLDER_PATH,
    RUN_TEMP_FOLDER_PATH,
    RUN_UTILITIES_FOLDER_PATH,
    RUN_SOURCES_FOLDER_PATH,
    RUN_CONSTANTS_FOLDER_PATH,
    AI_MODEL_PATH,
    GUI_FOLDER_PATH,
    GUI_CAMERA_B_PNG,
    GUI_CAMERA_R_PNG,
    GUI_MICROPHONE_R_PNG,
    GUI_MICROPHONE_B_PNG,
    GUI_NOTFOUND_PNG,
    GUI_PHONE_PNG,
    OTHER_CLUB_ICO_ICO,
    OTHER_CLUB_LOGO_PNG,
    OTHER_TEKNOFEST_LOGO_PNG,
    OTHER_TURKISH_LANGUAGE,
    OTHER_ENGLISH_LANGUAGE,
    ANIM_FOLDER_PATH,
    ANIM_ANIMATIONS,
    ANIM_DEFAULT,
    ANIM_DEFAULT_LISTENING,
    ANIM_teknofest,
    PROGRAM_STRUCTURE_CHECK_LIST,
    PROGRAM_PRE_EXITS_CHECK_LIST,
    PROGRAM_POST_CLEANUP_CHECK_LIST,
    PROGRAM_POST_CACHE_CHECK_LIST
)

from Constants.hashes import (
    ANIM_HASHES,
    TURKISH_CHARS
)