ANIM_HASHES = {
    "adin" : ["ad", "adi", "adlari", "adlar", "adlara"],
    "ev" : ["evi", "evleri", "evler", "eve", "evlere",],
    "gel" : ["gelmek", "geliyorlar", "geliyorsunuz", "gelin", "gelsin", "gelelim", "gelir", "geldi", "geliyor", "geliyorum", "geliyorsun", "geliyoruz"],
    "git" : ["gitmek", "gidiyorlar", "gidiyorsunuz", "gidin", "gitsin", "gidelim", "gider", "gitti", "gidiyor", "gidiyorum", "gidiyorsun", "gidiyoruz"],
    "gunaydin" : ["gunaydinlar"],
    "iyi misin" : ["iyi misiniz", "iyiler mi", "iyi miyiz", "iyi miyim", "iyi mi"], 
    "kac" : ["kaci", "kaca"],
    "masallah" : ["masallahiniz", "masallahlari", "masallahimiz", "masallahim", "masallahin", "masallahi"],
    "memleket" : ["memlekete", "memleketi", "memleketim", "memleketin", "memleketi", "memleketimiz", "memleketiniz"],
    "memnun" : ["memnunum", "memnunsun", "memnunuz", "memnunsunuz", "memnunlar"],
    "merhaba" : ["merhabalar"],
    "ne" : ["ney", "neydi", "nedir"],
    "neden" : ["nedenler", "nedenleri", "nedene", "nedeni", "nicin", "nicindir"],
    "ozur" : ["ozure", "ozuru", "ozurler"],
    "sagol" : ["sagolasin", "sagolasiniz", "sagolsunlar", "sagolun"],
    "sen" : ["seni", "sana", "senin", "senle",],
    "seviyorum" : ["seviyor", "seviyorlar", "seviyoruz", "sev", "sevmek", "seviyorsun", "seviyorsunuz"],
    "teknofest" : ["teknofesti", "teknofeste", "teknofestler"],
    "tesekkurler" : ["tesekkur"],
    "var" : ["varim", "varsin", "variz", "varsiniz", "varlar"],
    "yemek" : ["yemegi", "yemege", "yemekleri", "yemeklere"],
}

TURKISH_CHARS = {
    "ğ" : "g",
    "ü" : "u",
    "ş" : "s",
    "ö" : "o",
    "ç" : "c",
    "ı" : "i",
}